# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listr', '0004_auto_20160913_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='places',
            field=models.ManyToManyField(to='listr.Place'),
        ),
    ]
