# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listr', '0005_list_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listedplace',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='listedplace',
            name='in_list',
        ),
        migrations.RemoveField(
            model_name='listedplace',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='list_count',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ListedPlace',
        ),
    ]
