# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listr', '0006_auto_20160913_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='list_count',
            field=models.IntegerField(default=0),
        ),
    ]
