# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listr', '0007_auto_20160913_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
