# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listr', '0008_place_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='collaborators',
            field=models.ManyToManyField(related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
